#!/usr/bin/env bash
set -e

################################################################################
#
#   This script compiles and runs the tests for all problem solutions in
#   this repository. It is intended to be used for automated verification.
#
################################################################################

for chapter in $(ls -d */)
do
    cd $chapter

    for problem in $(ls -d */)
    do
        cd $problem

        if [ -e Makefile ]
        then
            make test > /dev/null
            echo "Passed tests for problem ${problem/\//}"
        else
            echo "Problem ${problem/\//} contains no tests"
        fi

        cd ..
    done

    cd ..
done

echo "Success: all tests passed!"
